# SPDX-License-Identifier: AGPL-3.0-or-later
# M0 spike (c) — temporary, own workspace, removed after the outcome is recorded.
[package]
name = "spike-slint-hello"
version = "0.0.0"
edition = "2024"
publish = false
license = "AGPL-3.0-or-later"

[dependencies]
slint = { version = "=1.18.1", default-features = false, features = ["std", "compat-1-2", "backend-winit", "renderer-femtovg", "accessibility"] }

[workspace]
