# SPDX-License-Identifier: AGPL-3.0-or-later
# M0 spike (b) — temporary, own workspace, removed after the outcome is recorded.
[package]
name = "spike-aws-lc"
version = "0.0.0"
edition = "2024"
publish = false
license = "AGPL-3.0-or-later"

[dependencies]
aws-lc-rs = { version = "=1.18.1" }

[workspace]
