# SPDX-License-Identifier: AGPL-3.0-or-later
[package]
name = "secmp-crypto"
description = "Typed cryptographic primitives and SecMP constructions (the only crate using crypto crates for SecMP constructions)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true
