# SPDX-License-Identifier: AGPL-3.0-or-later
[package]
name = "secmp-ui"
description = "SecMPro desktop UI (Slint) for Linux and Windows"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true
