// SPDX-License-Identifier: AGPL-3.0-or-later
#![cfg(feature = "kat")]
#![allow(clippy::unwrap_used, clippy::expect_used)]
#![forbid(unsafe_code)]
//! The frozen SecMP vectors (`vectors/<suite>.json`, cross-checked against the independent `ref/`
//! implementation, ADR-026) are regenerated by the Rust implementation on every target and must be
//! structurally identical (SCHEMA §1: `generator` ignored). Runs in the `kat` step on Linux, Windows and macOS.

#[path = "common/vectors.rs"]
mod vectors;

use serde_json::Value;

fn strip_generator(mut v: Value) -> Value {
    if let Some(m) = v.as_object_mut() {
        m.remove("generator");
    }
    v
}

fn check(suite: &str) {
    let frozen = strip_generator(secmp_testkit::kat::load(&format!("{suite}.json")));
    let ours = strip_generator(vectors::generate(suite));
    assert!(vectors::validate(&ours).is_empty(), "{suite}: hex fields");
    let (fc, oc) = (frozen.get("cases").unwrap(), ours.get("cases").unwrap());
    assert_eq!(fc.as_array().map(Vec::len), oc.as_array().map(Vec::len), "{suite}: number of cases");
    for (f, o) in fc.as_array().unwrap().iter().zip(oc.as_array().unwrap()) {
        assert_eq!(f, o, "{suite}: case {}", f.get("id").unwrap());
    }
    assert_eq!(frozen, ours, "{suite}: header");
}

#[test]
fn hkdf_labels() {
    check("hkdf-labels");
}

#[test]
fn caead() {
    check("caead");
}

#[test]
fn msgencrypt() {
    check("msgencrypt");
}

#[test]
fn hybridkem_768() {
    check("hybridkem-768");
}

#[test]
fn hybridkem_1024() {
    check("hybridkem-1024");
}

#[test]
fn hybridsign() {
    check("hybridsign");
}

#[test]
fn fingerprint() {
    check("fingerprint");
}

#[test]
fn sas() {
    check("sas");
}

#[test]
fn canonical_writer_is_stable() {
    // the Rust writer produces the canonical form of SCHEMA §1 (sorted keys, compact, ASCII, no newline)
    let doc = vectors::generate("sas");
    let text = vectors::canonical(&doc);
    assert!(!text.ends_with('\n') && !text.contains(": ") && !text.contains(", "));
    assert_eq!(serde_json::from_str::<Value>(&text).unwrap(), doc);
    assert_eq!(vectors::SUITES.len(), 8);
}
