# SPDX-License-Identifier: AGPL-3.0-or-later
"""Write SCHEMA-4.9-tr.md (SCHEMA §4.9, the `tr` case table) from the table that generates
vectors/tr.json, so that the two cannot drift apart.

    .venv/bin/python -m tools.render_schema_4_9          (from ref/)
"""

import collections
import pathlib

from secmp_ref import tr, tr_cases
from secmp_ref.tr_cases import KEYCHANGE_STREAM, MESSAGES, NEGATIVES, PHASES, ROUTE_STREAM

OUT = pathlib.Path(__file__).resolve().parent.parent.parent / "vectors" / "SCHEMA-4.9-tr.md"


def _fields(layout):
    return ", ".join(f"`{name}` {n}" for name, n in layout)


HEAD = """\
### 4.9 `tr` — SecMP-TR transcript (spec §7)

*SCHEMA §4.9 as proposed by `ref/` for brief REF-M3 (2026-09-30), from spec rev 2.3 §7, §3.2–3.4 and App. A–D. The
reviewer's decisions in the brief are written down as given; what `ref/` adds is marked **(proposal)**, and the
readings it pinned for SQ-22 … SQ-24 are marked with the question. The tables are generated by
`ref/tools/render_schema_4_9.py` from `ref/secmp_ref/tr_cases.py`, the table that generates `vectors/tr.json`.*

Suite `tr`, tag `tr` (SCHEMA §3), file `vectors/tr.json`, header `"schema": 4` and `"spec": "SecMP/1 rev 2.3"`
(SCHEMA §1). {total} cases, one per event, in event order:
{counts}.
Case *i* draws from its own stream (SCHEMA §2, suite name `tr`, index *i*). The ratchet takes its randomness from
that stream, every stream-derived value is listed in `inputs` in stream order, and the *derived* values follow them.

**Case shape (SCHEMA §1, `"schema": 4`).** Every case has `id` (`tr-0001` …), `op`, `party`, `inputs` and
`outputs`. `party` is the party whose state the event changes: `"A"` (the initiator) or `"B"` (the responder), and
`"AB"` for `init` **(proposal)**. The other case-level fields are ASCII strings, except `count`, which is a JSON
number. A `recv-reject` case carries `"expect": "reject"` **and** `outputs`, which hold its two state digests (they
are equal). Every value in `inputs` and `outputs` is a lowercase-hex byte string.

| op | case-level fields | `inputs`: stream order, then *derived* | `outputs` |
|---|---|---|---|
| `init` | `party` = `"AB"` | {init} | `state_post_A`, `state_post_B` |
| `send` | `party`, `msg` (`"m01"` … `"m40"`) | the Content's stream fields (below), `hdr_nonce` 24; *derived* `content` | `cell` (4096 B), `state_pre`, `state_post` |
| `recv` | `party`, `msg`, `from` (the id of the message's `send` case; the cell is not repeated) | on a DH step: {step} (DHRatchet order); otherwise none | `content`, `state_pre`, `state_post` |
| `advance` | `party`, `count` | `hdr_nonces` = 24 × `count` bytes, one `hdr_nonce` per cell, front to back | `state_pre`, `state_post` |
| `recv-reject` | `party`, `msg` and `from` (the base message and its `send` case) **(proposal)**, `manipulation`, `expect` = `"reject"` | the manipulation's stream fields (only N2: `ek_pq_seed` 64); for N1 only, {step}; then *derived* `cell` | `state_pre`, `state_post` |

**Obligations per op.** An implementation reproduces every case from its inputs and the preceding cases:

- `init`: `SK` = `sk` and `sb` = `sb`. The responder's `SPK_dh` key pair is the X25519 secret `spk_dh_sk`; its
  `RPK_kem` key pair is `KeyGen_internal(d ‖ z = rpk_kem_seed)` (ML-KEM-768). A is the §7.2 initiator with `dh_r` =
  X25519(`spk_dh_sk`, 9) and `kem_r` = the RPK `ek`; it draws `dh_s_sk`, `kem_s_seed` and `m` (dh_s keygen, kem_s
  keygen, `Encaps_internal(kem_r, m)`). B is the §7.2 responder and draws nothing. Both digests must match.
- `send`: Encrypt(state, `content`) (§7.3), with `hdr_nonce` as its randomness. `content` is the unpadded encoded
  Content (§7.6, D.5), and Encrypt pads it to `BODY_LEN` = 1710 (ISO/IEC 7816-4). The cell must equal `cell`, and
  the digests must match.
- `recv`: Decrypt(state, the `cell` of the case `from`) (§7.4), with `dh_sk`, `kem_seed` and `m` as DHRatchet's
  randomness (dh_s keygen, kem_s keygen, `Encaps_internal(kem_r, m)`). `inputs` is non-empty exactly when the
  message triggers a DH step. The plaintext, unpadded, must equal `content`, which is the sender's `content`.
- `advance`: `count` × Encrypt(state, Dummy), each with the next 24 bytes of `hdr_nonces`. The cells are discarded
  (lost in transit), and only the state digests are compared. The Dummy Content is `ver` 1, `type` 0x00, `seq` 0,
  `ts` 0, empty body **(proposal)**. No byte of the file depends on it.
- `recv-reject`: Decrypt(state, `cell`) fails with the implementation's single uniform error, and the state is left
  exactly as it was: `state_post` = `state_pre` (§7.4 note (c), transactional decrypt). N1 is rejected by the body
  MAC after DHRatchet has run on the working copy, so it lists DHRatchet's randomness like a `recv`.

**State digest** (brief REF-M3). It is a comparison construct of this suite, not a persistence format:

```
StateDigestV1 = SHA-256( "SecMP-TR/1 state-digest" ‖ sb ‖ rk ‖ dh_s.sk[32] ‖ opt(dh_r) ‖ kem_s.seed[64 = d ‖ z]
                ‖ opt(kem_r) ‖ opt(last_ct_r) ‖ opt(ct_s) ‖ opt(ck_s) ‖ opt(ck_r) ‖ opt(hk_s) ‖ opt(hk_r)
                ‖ opt(nhk_s) ‖ opt(nhk_r) ‖ u32be(n_s) ‖ u32be(n_r) ‖ u32be(pn) ‖ u32be(|skipped|)
                ‖ Σ_{{entries in insertion order}} ( hk[32] ‖ u32be(n) ‖ mk[32] ) )
opt(None) = 0x00 ; opt(Some(x)) = 0x01 ‖ x ; dh_s.sk = the 32 raw bytes as drawn (before clamping);
the ASCII label has no terminator.
```

The preimage contains every field of §7.1, so equal digests mean equal states. The label is not an App. A label
(SQ-24).

**Content per message.** Every Content has `ver` 1, `seq` = the message number (m07 → 7), `ts` = 1 700 000 000 +
`seq`, and is padded per D.5.

| content | body | stream fields, in order |
|---|---|---|
| Batch L | `count` 1 ‖ AppMessage{{`msg_id`, `kind` 1, `expire_after` 0, `payload_len` L, `payload`}} | `msg_id` 16, `payload` L (raw stream bytes: opaque at the encoding layer, §7.6 / SQ-19) |
| Dummy | empty | — |
| RouteUpdate | `count` 1 ‖ one RouteDescriptor built exactly as the §4.8 positive row `rd_relayqueue`: `ver` 1, kind 0x01, RelayQueue without `direct`, `period_s` 20 | {route} (`onion_seed` → `onion` as in §4.8) |
| Fragment idx k | `msg_id` ‖ `idx` k ‖ `total` 4 ‖ chunk k | idx 0 (m18): {kc}; idx 1–3: none |

**KeyChange** (m18–m21). KeyChange = new IKSPublic ‖ HybridSign(old `IK_sig`, `"SecMP-TR/1 keychange"`,
fingerprint(new IKSPublic)) (§7.6, §3.5, §6.2). The old `IK_sig` is Ed25519 seed `old_ik_ed_seed` ‖ ML-DSA-65
`KeyGen_internal(old_ik_mldsa_xi)`, and the ML-DSA part is hedged with `rnd`. The new IKSPublic is `ver` 1,
`ik_ed25519` from `new_ik_ed_seed`, `ik_mldsa65` from `new_ik_mldsa_xi`, and `ik_dh` = X25519(`new_ik_dh_sk`, 9).
The reassembled bytes `0x05 ‖ KeyChange` ({reassembled} B) are cut into maximal chunks of {chunk} B (1689 − 20),
with the remainder last: {chunks}.
All four fragments carry the same `msg_id`, `total` = 4 and `idx` = 0 … 3.

**m05 (SQ-22).** The brief's "m05 Batch L=1689" cannot be one cell: a Batch body is 24 + L bytes and `body_len` ≤ 1689
(§7.6), so L ≤ {lmax}. `ref/` pins **L = {lmax}**, which makes the body exactly 1689 B, the largest one-cell Batch.
This touches only the bytes of `content` and `cell` in the m05 `send` case and of `content` in its `recv` case.
No state digest depends on it.

#### Messages

| msg | sender → receiver | content | Content bytes (unpadded) | header `pn` | header `n` |
|---|---|---|---|---|---|
{messages}

#### Negative events

"ref check" names the check of the reference Decrypt that fires. It is informational; only the uniform rejection
and the unchanged state are compared. The checks are `cell-length` (split: the cell is not 4096 B), `no-header-key`
(no skipped hk, `hk_r` or `nhk_r` opens the header), `header-decode` (the header opens but HeaderV1 decoding
rejects), `step-same-dh` (a step with `dh_pk` = `dh_r`), `kem-constancy` (a non-step header whose `ek_pq`/`ct_pq`
differs from `kem_r`/`last_ct_r`), `replay` (`until` < `n_r`), `max-ff` (a gap > `MAX_FF`) and `body-mac`
(MsgDecrypt). Where a well-formed header is needed, the header is re-encoded and sealed again with the sender's
header key under the base cell's own `hdr_nonce` and AD `"SecMP-TR/1 hdr" ‖ sb`, and the body is unchanged
**(proposal: same nonce)**.

| N | case | party | position | base (send case) | `manipulation` | construction | ref check |
|---|---|---|---|---|---|---|---|
{negatives}

#### Transcript

The delivery order is the event order. Within a phase, the sender's `send` events come first, in send order, and
the deliveries follow in delivery order; phases 5 and 9 interleave as the brief writes them **(proposal)**. A
negative event sits immediately before or after the delivery the brief names. For a `send`, `pn`/`n` are the
header's; for a `recv`, they are the delivered header's; for an `advance`, `n` is the range of the discarded
cells. "|skipped|" is the party's `skipped` after the event, "Δ" the entries inserted (+) and removed (−), and
"path" says whether the message was decrypted through §7.4 step 1 (`skipped`) or on a chain.

{phases}

| # | id | ph | op | party | msg | from | content / manipulation | `pn` | `n` | step | \\|skipped\\| | Δ | path / ref check |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
{transcript}

#### Readings and questions

- **SQ-22** (m05): L = {lmax}, as above.
- **SQ-23** (N9): the brief says "sealed under the sender's `nhk_s`". Taken literally, that is B's `nhk_s` at the
  time, the header key of B's *next* chain, and none of A's keys opens it: N9 would test `no-header-key`, not the
  `dh_pk` = `dh_r` check. `ref/` pins the key m16 is sealed under: B's `hk_s` at m16, which is A's `nhk_r` and was
  B's `nhk_s` until B's step on m14. N9 then opens under `nhk_r`, takes the step branch and is rejected by
  `step-same-dh` before any KDF. Only the `cell` of N9 depends on this. Under both readings the outcome is a
  rejection with the state unchanged.
- **SQ-24** (state digest): the label `"SecMP-TR/1 state-digest"` is not in App. A, which calls itself exhaustive
  and requires an ADR for any new label. It is prefix-free against App. A (tested), and it is used only for this
  digest. Non-blocking.
- Readings adopted without a question (`ref/SPEC-QUESTIONS.md`, "Readings adopted without a question — REF-M3"):
  Open() includes HeaderV1 decoding, and a header that opens but does not decode rejects the cell (N11); the
  §7.4 step-1 path checks neither KEM constancy nor `dh_pk`, as written; the Content is decoded after Decrypt and is
  not part of its transaction; `n_r` = 2^32 − 1 before the increment rejects; the interleaving, same-nonce re-seal,
  advance Dummy Content, `party` = `"AB"` and `msg`/`from` on `recv-reject` above.
"""


def _counts(cases):
    c = collections.Counter(x.op for x in cases)
    return ", ".join(f"{c[op]} `{op}`" for op in ("init", "send", "recv", "advance", "recv-reject"))


def _messages_table(run):
    sends = {r["msg"]: r for r in run.rows if r["op"] == "send"}
    out = []
    for n, m in MESSAGES.items():
        r = sends[tr_cases.msg_name(n)]
        out.append(f"| {r['msg']} | {m.sender} → {tr_cases.other(m.sender)} | {tr_cases.describe(n)} | "
                   f"{r['content_len']} | {r['pn']} | {r['n']} |")
    return "\n".join(out)


def _position(rows, k):
    """Where negative row k sits: before the next delivery to its party, or else after the previous one
    (adjacent negatives are skipped over)."""
    party = rows[k]["party"]
    nxt = next(r for r in rows[k + 1:] if r["op"] != "recv-reject")
    if nxt["op"] == "recv" and nxt["party"] == party:
        return f"before {party}'s recv {nxt['msg']}"
    prev = next(r for r in reversed(rows[:k]) if r["op"] != "recv-reject")
    assert prev["op"] == "recv" and prev["party"] == party
    return f"after {party}'s recv {prev['msg']}"


def _negatives_table(run):
    out = []
    negs = [(k, r) for k, r in enumerate(run.rows) if r["op"] == "recv-reject"]
    for k, r in sorted(negs, key=lambda kr: int(kr[1]["neg"][1:])):
        neg = NEGATIVES[r["neg"]]
        out.append(f"| {r['neg']} | {r['id']} | {r['party']} | {_position(run.rows, k)} | {r['msg']} ({r['frm']}) | "
                   f"`{neg.manipulation}` | {neg.text} | `{neg.rule}` |")
    return "\n".join(out)


def _transcript_table(run):
    out = []
    for r in run.rows:
        op = r["op"]
        cells = [str(r["i"]), r["id"], str(r["phase"]), f"`{op}`", r.get("party", "")]
        if op == "init":
            cells += ["", "", "", "", "", "", "", "", ""]
        elif op == "send":
            cells += [r["msg"], "", r["content"], str(r["pn"]), str(r["n"]), "", str(r["skipped"]), "", ""]
        elif op == "recv":
            delta = " ".join(x for x in (f"+{r['inserted']}" if r["inserted"] else "",
                                         f"−{r['removed']}" if r["removed"] else "") if x)
            cells += [r["msg"], r["frm"], r["content"], str(r["pn"]), str(r["n"]), "step" if r["step"] else "",
                      str(r["skipped"]), delta, r["via"]]
        elif op == "advance":
            cells += [f"×{r['count']}", "", "Dummy (discarded)", str(r["pn"]), r["n"], "", str(r["skipped"]), "", ""]
        else:
            cells += [r["msg"], r["frm"], f"{r['neg']} `{r['manipulation']}`", "", "", "", str(r["skipped"]), "",
                      f"`{r['rule']}`"]
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out)


def _phases():
    return "\n".join(f"- **Phase {p}** — {text}" for p, text, _ in PHASES)


def render() -> str:
    run = tr_cases.run()
    kc = tr_cases.KEYCHANGE_REASSEMBLED
    chunks = [min(tr_cases.FRAGMENT_CHUNK, kc - k * tr_cases.FRAGMENT_CHUNK) for k in range(tr_cases.KEYCHANGE_TOTAL)]
    return HEAD.format(
        total=len(run.cases), counts=_counts(run.cases),
        init=_fields(tr_cases.INIT_STREAM + tr_cases.INIT_DRAWS), step=_fields(tr_cases.STEP_DRAWS),
        route=_fields(ROUTE_STREAM), kc=_fields(KEYCHANGE_STREAM), reassembled=kc, chunk=tr_cases.FRAGMENT_CHUNK,
        chunks=", ".join(f"{c} B" for c in chunks), lmax=tr_cases.BATCH_MAX_L,
        messages=_messages_table(run), negatives=_negatives_table(run), phases=_phases(),
        transcript=_transcript_table(run))


def main():
    text = render()
    assert tr.SKIP_WINDOW == 256 and tr.MAX_FF == 2**20
    OUT.write_text(text, encoding="utf-8")
    print(f"{OUT.name}: {len(text.splitlines())} lines")


if __name__ == "__main__":
    main()
