# SPDX-License-Identifier: AGPL-3.0-or-later
"""Write SCHEMA-4.11-link.md (SCHEMA §4.11, the `link` case table) from the table that generates
vectors/link.json, so that the two cannot drift apart. The prose is the reviewer's (brief REF-M5);
the counters, answers, sizes and reference checks in the tables are the run's own, and the run asserts
that each equals the reviewer's.

    .venv/bin/python -m tools.render_schema_4_11          (from ref/)
"""

import pathlib

from secmp_ref import link_cases as lc
from secmp_ref import relay

OUT = pathlib.Path(__file__).resolve().parent.parent.parent / "SCHEMA-4.11-link.md"

HEAD = """\
### 4.11 `link` — SecMP-LINK/SecMP-Q full run (spec §8, §9)

*SCHEMA §4.11 as decided by the reviewer for brief REF-M5 (2026-10-02). Sources: spec rev 2.3 §8 and §9, with
§3.2, §3.4–3.5, §4, App. A, B and D. `docs/03:<line>` is a line of `03-protocol-spec.md` rev 2.3. The planning cell
raised thirteen open points; the reviewer decided all of them, and the readings are stated below as "reading OPEN-n".
The tables are generated by `ref/tools/render_schema_4_11.py` from `ref/secmp_ref/link_cases.py`, the table that
generates `vectors/link.json`: the counters, answers, sizes and reference checks in them are the run's own, and the
run asserts that each equals the reviewer's. What `ref/` adds is marked **(proposal)**; its questions SQ-26 … SQ-28
block no case (end of this section).*

*Earlier answers that bind this suite:*
- *SQ-12: the decoder obligations, now docs/03:152.*
- *SQ-20: App. D governs `ver`. Frame plaintexts have none; HELLO, HS1, HS2 and RelayInfoV1 do.*
- *SQ-21: `op`/`mode` names.*
- *REF-M2 readings, all confirmed: 2 (record `len` = |body| including the type byte), 5 (boolean `u8` ∈ {{0, 1}}),
  8 (CONT `idx` ∈ {{1, 2}}, `data` 4100 B), 9 (CELLR decoded with its request as context), 10 (LINK_GET mode 0 has
  `sig` = 0^64) and 13 (D.6: the FETCH_MULTI count is not signed; LINK_PUT signs SHA-256 of the whole 12360-B blob;
  `cmd_seq` is u32 BE).*
- *SQ-13 and SQ-14 (RelayRef) do not touch this suite's wire: no RelayRef bytes occur here. The client holds only
  the `relay_fp` and the access key that a RelayRef would give it.*
- *The ref-log notes L-3 and L-5 are answered by readings OPEN-7 and OPEN-11.*

Suite `link`, tag `link` (SCHEMA §3), file `vectors/link.json`, header `"schema": 6` and `"spec": "SecMP/1 rev 2.3"`
(SCHEMA §1). The suite has {total} cases, run by one client C and one relay R. There is one handshake, and then one link
("link A") on which every command case runs in event order. The case groups are:
- {n_pos} positive cases: {n_hs} for the handshake and {n_pos_a} on link A;
- {n_err} command-error cases (E1–E{n_err}), in which the relay answers with an error;
- {n_x} indistinguishability case (X1);
- {n_ri} RelayInfo cases: I1–I{n_ri_rej} `relayinfo-reject`, plus I{n_ri}, an accepting boundary case;
- {n_hs1} `hs1-reject` cases (H1, S1–S{n_s});
- {n_hs2} `hs2-reject` cases (T1–T{n_hs2});
- {n_fr} `frame-reject` cases (F1–F{n_fr}).

Of these, {n_expect} carry `expect: reject`.

The order is as follows:
1. The positives and the command-error cases interleaved in event order, `link-0001` … `link-0050`. E1 and E2 sit
   where their state exists, as tr interleaves its events (SCHEMA §1, `"schema": 4`).
2. X1 (`link-0051`).
3. The RelayInfo cases (`link-0052` … `link-0059`).
4. `hs1-reject`, then `hs2-reject`, then `frame-reject` (`link-0060` … `link-0086`).

The cases of points 3 and 4 are each evaluated on a copy of a named state and change nothing.

Case *i* draws from its own stream (SCHEMA §2, suite name `link`, index *i*). Every stream-derived value is listed in
`inputs` in stream order: the client's draws first, then the relay's draws in response-frame order. The *derived*
values follow them. Ed25519 signatures (deterministic) and tokens (HMAC) draw nothing.

**Case shape (SCHEMA §1, `"schema": 6`).**
- **Common fields.** Every case has `id` (`link-0001` …), `op`, `party`, `from` and `inputs`.
- **`party`.** One of:
  - `"C"`: the client;
  - `"R"`: the relay;
  - `"CR"`: one request/response round trip on link A. C builds and seals, R opens, executes and answers, C opens.
- **`from`.** The id of the case whose state this case starts from:
  - in the handshake, the preceding step;
  - on link A, the preceding link-A case;
  - in a reject case, the base state named in its row.

  `link-0001` starts from no state and has no `from` **(proposal)**.
- **Link-A fields.** A link-A case also carries `cmd_seq`, a JSON number: the `cmd_seq` of its first request frame.
  `send-fill` also carries `count`.
- **Command-error case.** Carries `manipulation` and `outputs`, and no `expect`. The relay's answer is a defined
  response, not a rejection. Its `outputs` are `req`, `req_frames`, `resp`, `resp_frames`, `link_post` and
  `store_post` **(proposal)**: the manipulated token or signature is visible in `req`.
- **I8.** A `relayinfo-accept` case with `manipulation`. Its `outputs` are {{`accept`}}.
- **`expect: reject` case.** Carries `manipulation` and `"expect": "reject"`.
  - `relayinfo-reject`, `hs1-reject` and `hs2-reject` cases have no `outputs`, because no link exists yet. S10 is
    the exception and carries the outputs its row names.
  - A `frame-reject` case carries `outputs` = {{`link_post`}}, unchanged, as hx's `respond-reject` carries
    `opks_post`.
- **X1.** Carries `cases`, an array of arrays of case ids, instead of `from`.

**Values.** Values are lowercase-hex byte strings, except the following:
- `accept` is a JSON boolean.
- `req`, `req_frames`, `resp` and `resp_frames` are JSON arrays of byte strings in frame order.
  - `req`/`resp` hold the **unpadded** frame payloads `op ‖ cmd_seq ‖ fields` (docs/03:806). The padding to 4336 B is
    the §4.1 rule (docs/03:149) and is implied.
  - `req_frames`/`resp_frames` hold the 4352-B wire frames.
- `link_post` is a JSON object {{`c2r`, `r2c`, `cmd_seq`}} of numbers: the next frame counter in each direction
  (docs/03:566) and the relay's last recorded `cmd_seq` (reading OPEN-5).
- `store_post` is a JSON object {{`queues`, `linkdata`}}.
  - `queues` is an array, ascending by `rid`, of {{`rid`, `sid`, `cell_ids` (numbers in queue order), `next_cell_id`}}
    (docs/03:583).
  - `linkdata` is an array, ascending by `ld_id`, of {{`ld_id`, `one_time`, `expires_bucket`, `present`, `consumed`}}. A
    consumed one-time entry stays as `present` 0, `consumed` 1 (docs/03:610).
  - Hour buckets and `arrival` are not listed (docs/03:583, 624). They are relay-internal and never on the wire, and
    `arrival` matters only through the order of FETCH_MULTI responses.
- `resp_counts` (X1) is an array of arrays of numbers, and `frame_len` (X1) is a number **(proposal: its JSON shape)**.

The suite's constants are not repeated in `inputs`.

**Constants.**

| Constant | Value | Source |
|---|---|---|
| `now` | {now} (hour bucket ⌊now/3600⌋ = {bucket}) | as §4.10; buckets are hours since epoch, `u32` (docs/03:583) |
| `ver` | 0x01 in HELLO, RelayInfoV1, HS1 and HS2 | docs/03:161, 795–799 |
| `kid` | {kid} (the relay holds no other `kid`) | `kid: u32` (docs/03:528, 797) |
| `valid_until` | {valid_until} (`now` + {validity} s, under 30 days) | `valid_until ≥ now`, `valid_until − now ≤ 60 days` (docs/03:535; reading OPEN-4) |
| `cmd_seq` | 1 for the first command on link A, then +1 per command; link-0023 skips one (+2); CONT repeats it | strictly increasing (docs/03:589) |
| `one_time` | {one_time} | docs/03:197, 610 |
| `expires_bucket` | {expires_bucket} (= {bucket} + 168, seven days) | within `LINKDATA_TTL` (docs/03:173) |
| `F`, `F_M`, `QUEUE_CAPACITY` | {f}, {f_m}, {capacity} | docs/03:166–168; `F` and `F_M` are tunable until M6 (docs/03:182, ADR-018), and these cases change with them |
| `budget_queues` | {budget} (a vector-only relay parameter) | reading OPEN-12 (docs/03:625) |
| order-8 point | `{low_order}` | as SCHEMA §4.4 row 16 and §4.10 R5 |
| bad ML-KEM ek | bytes 0–2 := `ff ff ff` | as SCHEMA §4.4 row 17 |

The relay's static keys are not table values. They come from case 1's stream: `relay_sig`, and `relay_dh` and
`relay_kem` of `kid` 1 (docs/03:528). `sess_id` is never a table value; it is derived in link-0004 and link-0005
(docs/03:553). Where a row needs "another link's" `sess_id`, it uses `flip(sess_id, 0)` (SCHEMA §4 manipulations).
Queue **A** is the queue of link-0006's keys, and queue **B** that of link-0015's keys. **L** is the link-data entry
of link-0025.

**Keys from the stream** (SCHEMA §2).
- An X25519 secret is 32 raw bytes.
- An Ed25519 key is a 32-byte seed. This covers `relay_sig` and the queue keys `recv_pk`/`send_pk` and `owner_pk`,
  which docs/03:152 lists as Ed25519 keys.
- An ML-KEM key pair is `KeyGen_internal(d ‖ z)` of a 64-byte seed. `relay_kem` is ML-KEM-1024 (docs/03:70) and `ek_c`
  is ML-KEM-768 (docs/03:71).
- `m*` is `Encaps_internal` randomness.
- `relay_access_key`, cells, blobs, `ld_id` and dummies are raw stream bytes.

**Obligations per op.** An implementation reproduces every case from its inputs and the cases before it.

- `relay-keys` (R):
  - `relay_sig_pk` comes from `relay_sig_seed`.
  - `relay_fp` = SHA-256(`"SecMP-LINK/1 relay-fp"` ‖ `relay_sig_pk`) (docs/03:528, 220).
  - `relay_dh_pk` = X25519(`relay_dh_sk`); (`relay_kem_ek`, `relay_kem_dk`) come from `relay_kem_seed`.
  - `akc` = SHA-256(`"SecMP-Q/1 akc"` ‖ `relay_access_key`) (docs/03:222, 618).
  - `relayinfo` = RelayInfoV1 {{`ver`, `relay_sig_pk`, `kid`, `relay_dh_pk`, `relay_kem_ek`, `akc`, `valid_until`,
    `sig`}}, 1741 B (docs/03:531–532, 799, 779). `sig` = Ed25519(`relay_sig`, `"SecMP-LINK/1 relayinfo"` ‖ the 1677
    encoded bytes before `sig`).
  - `rec_relayinfo` = `len` (1742) ‖ 0x02 ‖ RelayInfoV1, 1744 B (docs/03:792, 796).
- `relayinfo-accept` (C): the client pins `relay_fp`, holds `relay_access_key` (both from case 1) and knows `now`.
  1. It emits `rec_hello` = `len` (7) ‖ 0x01 ‖ `"SECMP"` ‖ 0x01, 9 B (docs/03:540, 795).
  2. It processes case 1's `rec_relayinfo` and decodes it with the §4.1 obligations (docs/03:152): `relay_sig_pk`,
     the R and S of `sig`, `relay_dh_pk` not low-order, and the `relay_kem_ek` modulus check.
  3. It verifies `sig`, `relay_fp`, `valid_until ≥ now` and `akc` (docs/03:535), and `valid_until − now ≤ 60 days`
     (5 184 000 s; reading OPEN-4).
  4. It uses the info only for this link (docs/03:535).

  Outputs: `rec_hello`, `accept` = true. I8 lists only `accept`.
- `hs1` (C):
  - `e_c` = X25519(`e_c_sk`); (`ek_c`, `dk_c`) = ML-KEM-768 `KeyGen_internal(ek_c_seed)`.
  - (`pk_e1`, `ct_kem`), `ss1` = HybridKEM-1024.Encaps((`relay_dh_pk`, `relay_kem_ek`)) with `V` =
    `"SecMP-HybridKEM-1024/1"`. It draws `sk_e1` and then `m1` (docs/03:92, 94, 542, 546; reading OPEN-1).
  - `h0` = SHA-256(`"SecMP-LINK/1 h0"` ‖ 0x01 ‖ u32be(`kid`) ‖ `relay_fp` ‖ `e_c` ‖ SHA-256(`ek_c`) ‖ `pk_e1` ‖
    SHA-256(`ct_kem`)) (docs/03:545).
  - `ck1` = HKDF-Extract(salt = `h0`, IKM = `ss1`) (docs/03:547).
  - `mac1` = HMAC-SHA-256(`ck1`, `"SecMP-LINK/1 hs1"`) (docs/03:548).
  - `hs1` = `ver` ‖ `kid` ‖ `e_c` ‖ `ek_c` ‖ `pk_e1` ‖ `ct_kem` ‖ `mac1`, 2853 B.
  - `rec_hs1` = `len` (2854) ‖ 0x03 ‖ `hs1`, 2856 B (docs/03:797).
- `hs2` (R):
  1. R decodes `rec_hs1` (`e_c` and `pk_e1` not low-order, the `ek_c` modulus check; docs/03:152) and checks that
     `kid` is held.
  2. `ss1` = HybridKEM-1024.Decaps((`relay_dh_sk`, `relay_kem_dk`), (`pk_e1`, `ct_kem`)). The combiner hashes R's own
     `relay_dh_pk` and `relay_kem_ek` (docs/03:98–101; SCHEMA rev 2 reading 3).
  3. It computes `h0` and `ck1`, and compares `mac1` in constant time before it responds (docs/03:548).
  4. Only then does it draw `sk_er` and `m2` (readings OPEN-1 and OPEN-2). (`e_r` = pk_e, `ct_c`), `ss2` =
     HybridKEM-768.Encaps((`e_c`, `ek_c`)) with `V` = `"SecMP-HybridKEM-768/1"` (docs/03:549).
  5. `h1` = SHA-256(`h0` ‖ `mac1` ‖ `e_r` ‖ SHA-256(`ct_c`)) (docs/03:550).
  6. `ck2` = HKDF-Extract(salt = `h1`, IKM = `ck1` ‖ `ss2`) (docs/03:551).
  7. `mac2` = HMAC-SHA-256(`ck2`, `"SecMP-LINK/1 hs2"`) (docs/03:552).
  8. (`k_c2r` ‖ `k_r2c` ‖ `sess_id`) = HKDF-Expand(PRK = `ck2`, `"SecMP-LINK/1 keys"`, 80), split 32/32/16
     (docs/03:553; SCHEMA §4.1 row 9).
  9. `hs2` = `ver` ‖ `e_r` ‖ `ct_c` ‖ `mac2`, 1153 B; `rec_hs2` = `len` (1154) ‖ 0x04 ‖ `hs2`, 1156 B (docs/03:798).
- `hs2-accept` (C):
  - C decodes `rec_hs2` (`e_r` not low-order).
  - `ss2` = HybridKEM-768.Decaps((`e_c_sk`, `dk_c`), (`e_r`, `ct_c`)).
  - It computes `h1` and `ck2`, compares `mac2` in constant time (docs/03:552), and derives the keys.
  - `ss2`, `h1`, `ck2`, `k_c2r`, `k_r2c` and `sess_id` equal case 4: asserted.
- Every link-A case (CR):
  1. C writes each request payload (D.2, docs/03:806–818) with the row's `cmd_seq`, and signs where D.6 says
     (docs/03:589, 880). The token is HMAC-SHA-256(`relay_access_key`, `"SecMP-Q/1 token"` ‖ `sess_id` ‖
     u32be(`cmd_seq`)) (docs/03:618, 589, 148).
  2. C seals each frame as XChaCha20-Poly1305.Seal(`k_c2r`, 0^16 ‖ u64be(`c2r`), `"SecMP-LINK/1 frame"` ‖ `sess_id`,
     pad(payload, 4336)) (docs/03:563).
  3. R opens each frame with the expected counter, strict +1 (docs/03:566). It decodes the request and executes §9
     (docs/03:572–629).
  4. R answers with exactly the D.2 number of frames, in request order, under `k_r2c` (docs/03:627, 833).
  5. C opens and decodes the response frames (a CELLR with its request as context).

  Outputs: `req`, `req_frames`, `resp`, `resp_frames`, the row's derived values, `link_post` and `store_post`. Both
  sides' counters agree after every case: asserted. The derived values are, by command **(proposal: the names)**:
  QUEUE_NEW `token` and `sig`, and `rid`, `sid` on the first QUEUE_NEW of a queue; SEND, FETCH, QUEUE_DEL `sig`;
  FETCH_MULTI `sig_0`, `sig_1` in entry order; LINK_PUT `token`, `sig`; LINK_GET in owner-status mode `sig`, in
  consume mode none (its `sig` is 0^64); PING none.
- `send-fill` (CR): `count` honest SENDs of the same `fill_cell` to one queue, with `cmd_seq` and the counters +1
  each. Outputs:
  - `frames_sha256`: SHA-256 of the 2 × `count` wire frames in event order (req₁ ‖ resp₁ ‖ … ‖ req_count ‖
    resp_count), as tr's `advance` summarises its cells;
  - `resp_last`: the last OK_SEND payload;
  - `link_post` and `store_post`.
- Command-error cases: as their command, with the manipulation in the row. The relay executes nothing and changes
  nothing in the store. The frame counters advance like those of any other request, and so does the recorded
  `cmd_seq`, wherever it exceeds `last` (reading OPEN-5).
- `relayinfo-reject` (C, from link-0001), `hs1-reject` (R, relay state = link-0001) and `hs2-reject` (C, client state
  = link-0003): the receiver rejects with its single uniform error (reading OPEN-2). It emits nothing more, closes
  the connection, draws nothing and keeps no state. S10 differs: see its row.
- `frame-reject` (R or C, from link-0008: R expects `c2r` = 3, C expects `r2c` = 3, `last` = 3): the receiver gets
  one unit and rejects it with the uniform LINK-level error (readings OPEN-2 and OPEN-6). Its counters, `cmd_seq` and
  store are unchanged, so `link_post` = {{3, 3, 3}}.
  - A unit of any length other than 4352 B is rejected before the AEAD ("every frame is exactly 4352 B",
    docs/03:566; the stream has no length prefix, docs/03:802).
  - A frame that opens but does not decode, or a CONT with no multi-frame command pending, is rejected the same way
    (reading OPEN-6).

"ref check" in the reject tables names the check of the reference that fires. It is informational: only the uniform
rejection is compared, as in §4.10. The reference's checks are `ri-decode`, `ri-sig`, `ri-fp`, `ri-expired`,
`ri-validity` and `ri-akc` (RelayInfo, in this order); `hello-decode`, `hs1-decode`, `kid-unknown` and `mac1` (R on
HS1); `hs2-decode` and `mac2` (C on HS2); `frame-len`, `frame-open` and `pt-decode` (padding, opcode or fields) and
`cont-orphan` on a frame.

#### Positive cases

In the counter column, `c2r` and `r2c` are the frame counters the case uses (docs/03:566). Each counts from 0 in its
direction. In the outputs, `resp` is followed by its decoded answer: OK_SEND {{`cell_id`, `evicted_present`,
`evicted_id`}}, CELLR {{`present`, `rid`, `cell_id`}} (`rid` 0, A or B), LINKR {{`present`, `consumed`}}; `store_post`
is written as queue: [`cell_ids`], next `next_cell_id`, and L: `one_time`, `expires_bucket`, `present`, `consumed`.

| # | id | op | party | from | `cmd_seq`; `c2r`; `r2c` | `inputs`: stream order; *derived* | `outputs` (B) | step |
|---|---|---|---|---|---|---|---|---|
{positives}

#### Command-error cases (in event order; `manipulation`, `outputs`, no `expect`)

The answer column gives the D.2 response (docs/03:824–830). The ERR codes are 1 TOKEN, 2 FULL, 3 NOQUEUE, 4 AUTH,
5 EXISTS and 6 MALFORMED. "Fresh" keys are drawn from the case's own stream.

Each row has exactly one fault, because the spec gives no order among the checks (docs/03:595, 600, 625). Every row
has the same frame count under the decided readings, so its counters are fixed.

| E | id | op | `manipulation` | `cmd_seq`; `c2r`; `r2c` | `inputs`: stream order; *derived* | construction | answer; store | spec |
|---|---|---|---|---|---|---|---|---|
{errors}

#### Indistinguishability (X1)

| X | id | op | party | `cases` | `outputs` |
|---|---|---|---|---|---|
{x1}

The seven groups compare a success with the errors of the same command:

| Group | Cases |
|---|---|
{groups}

X1 draws nothing and changes nothing.

**What the byte-level test compares, per group.** docs/03:606 says "success and error frames are indistinguishable on
the wire" (see also the 07 M5 acceptance). The test checks four things:
1. The number of relay→client frames, which equals the D.2 count for the command (docs/03:597–602, 833).
2. The position of the response in the frame sequence: right after the command's last request frame. For LINK_PUT,
   that is after the third frame (docs/03:818).
3. The length of every frame: 4352 B (docs/03:163, 566).
4. The length of every plaintext before sealing: 4336 B, ISO/IEC 7816-4 padded (docs/03:149, 563).

Nothing else is observable on the wire. A frame carries no cleartext byte: there is no length prefix (docs/03:802),
and the nonce is implicit (docs/03:563). Equal counts, positions and lengths are therefore the whole wire-level claim.
That the contents cannot be told apart is the AEAD's property and cannot be tested from a vector. Timing is outside
the suite (M6).

`resp_counts` is the vector's statement of item 1. Items 2–4 hold for every case in the file, and the generator
asserts them.

#### RelayInfo cases (party C, from link-0001; the client pins case 1's `relay_fp` and holds its access key)

| I | id | op | `manipulation` | `inputs`: *derived* | construction | outcome / ref check |
|---|---|---|---|---|---|---|
{relayinfo}

No case sits on the `valid_until ≥ now` boundary. I8 sits on the 60-day boundary.

#### `hs1-reject` (party R; relay state = link-0001; base = link-0003's honest records)

| S | id | `manipulation` | `inputs`: stream order; *derived* | construction | ref check |
|---|---|---|---|---|---|
{hs1}

#### `hs2-reject` (party C; client state = link-0003; base = link-0004's `rec_hs2`)

Each case lists *`rec_hs2`* (derived) and draws nothing.

| T | id | `manipulation` | construction | ref check |
|---|---|---|---|---|
{hs2}

#### `frame-reject` (from link-0008; base = link-0009's request or response payload and frames)

Each case lists *`frame`* (derived) and has `outputs` = {{`link_post`: {{3, 3, 3}}}}. The receiver's state is unchanged
(readings OPEN-2 and OPEN-6). Only F10 draws from the stream.

| F | id | party | `manipulation` | construction | ref check |
|---|---|---|---|---|---|
{frames}

Two limits are not reachable in a vector: counter overflow (`checked_add`, docs/03:566) and `LINK_MAX_FRAMES`
(docs/03:179). The latter is also the client's re-handshake rule, not a relay check.

#### Readings decided by the reviewer (planning-cell items OPEN-1 … OPEN-13)

- **Reading OPEN-1 — draw order** (docs/03:542, 549, 92–94).
  - C draws `e_c_sk`, `ek_c_seed`, `sk_e1`, then `m1`. R draws `sk_er`, then `m2`.
  - This is the HS1 field order combined with the §3.2 line order (X25519.keygen before ML-KEM.Encaps), as in
    REF-M3 reading 3.
  - Cases: P3, P4, S4, S10.
- **Reading OPEN-2 — LINK-level rejection** (docs/03:535, 548, 552, 566, 628).
  - A failed RelayInfo, HELLO, HS1, HS2 or frame check is one uniform error. The receiver emits nothing more (no
    RELAYINFO, HS2 or frame) and closes the connection.
  - Its counters, `cmd_seq` and store are unchanged.
  - R draws no HS2 randomness before `mac1` verifies.
  - Cases: I1–I7, H1, S1–S10, T1–T4, F1–F12.
- **Reading OPEN-3 — HS1 replay** (docs/03:556, 701; there is no HS1 cache).
  - R answers a replayed HS1 as a new handshake, with a fresh `e_r` and `ct_c`.
  - Replay resistance comes from `ss2`: the replayed first frame fails under the new `k_c2r`.
  - Case: S10.
- **Reading OPEN-4 — the 60-day bound** (docs/03:535).
  - The client MUST check `valid_until − now ≤ 60 days` and reject a RelayInfo that exceeds it. This makes the bound
    enforceable rather than an operator promise.
  - Exactly 60 days is accepted.
  - Cases: P2, I7, I8.
- **Reading OPEN-5 — `cmd_seq`** (docs/03:589).
  - `last` starts at 0.
  - Every request frame that opens and has `cmd_seq` > `last` records its `cmd_seq`, whatever the command's outcome.
  - `cmd_seq ≤ last` is answered with one ERR 6 (MALFORMED), and nothing is executed. CONT stays exempt.
  - Cases: E23; `link_post` everywhere.
- **Reading OPEN-6 — undecodable frames** (docs/03:149, 155, 628, 833; contrast docs/03:810).
  - A frame that opens but does not decode is a LINK-level rejection under reading OPEN-2: teardown, nothing
    emitted, counters unchanged. Bad padding and an unknown opcode are examples.
  - A CONT with no multi-frame command pending is rejected the same way.
  - SKEY (0x02) is the one reserved opcode that is answered, with ERR 6 (docs/03:810).
  - Cases: F10–F12, E21.
- **Reading OPEN-7 — the FETCH response layout** (docs/03:585, 597, 604, 827, 833; ref-log note L-3).
  - A FETCH error is answered with exactly `F` CELLR frames. Frame 1 has `present` ∈ {{2, 3, 4}}, `rid` set,
    `cell_id` 0 and a random cell. Frames 2 … `F` are dummies.
  - §9.1's "answer … with `ERR_MALFORMED`" reads as `present` = 4.
  - In a successful FETCH, the real cells come first, ascending by `cell_id`, and the dummies follow.
  - Cases: P12–P14, P21, E11–E14.
- **Reading OPEN-8 — FETCH_MULTI** (docs/03:598, 604, 827).
  - Each entry has the FETCH `ack` semantics: cells with `cell_id` ≤ `ack` are deleted first, and `ack ≥
    next_cell_id` gives `present` 4 for that entry.
  - The error frames come first, in request order.
  - A present-1 CELLR carries its queue's `rid`. docs/03:827 zeroes `rid` "for FETCH" only.
  - Cases: P18, E15.
- **Reading OPEN-9 — signature failures that §9.3 does not list** (docs/03:595, 599, 600; compare 596 and 629).
  - QUEUE_NEW, QUEUE_DEL and LINK_PUT answer a signature that does not verify with ERR 4 (AUTH). For LINK_PUT, the
    answer comes after the third frame (docs/03:818). The state is unchanged.
  - QUEUE_DEL of an unknown `rid` is answered with ERR 3. No case tests it.
  - Cases: E7, E16, E18.
- **Reading OPEN-10 — LINK_GET owner status with a signature that does not verify** (docs/03:601, 606, 610, 833).
  - The answer is three frames: LINKR {{`present` 0, `consumed` 0, dummy blob}}, then CONT, CONT.
  - This gives no existence oracle, and the frame count equals that of a success.
  - Case: E22.
- **Reading OPEN-11 — LINKR fields** (docs/03:601, 610, 827; ref-log note L-5).
  - The consuming call answers `present` 1, `consumed` 0.
  - The dummy blob is 12360 random bytes from R's stream, split 4160 / 4100 / 4100 like a blob.
  - Cases: P25–P27, E19, E20, E22.
- **Reading OPEN-12 — the budget** (docs/03:625).
  - `budget_queues` = 2 is a vector-only relay parameter. Queues count; link data does not.
  - "Exceeded" means a QUEUE_NEW that would create a third queue.
  - The table never sends an identical QUEUE_NEW at the limit.
  - Cases: E1, P15, P16.
- **Reading OPEN-13 — the first three frames each way** (docs/03:560, 784).
  - The frames are QUEUE_NEW, SEND and PING, at counters 0, 1 and 2.
  - A real client runs QUEUE_NEW on a one-shot link (docs/03:686). That is client behaviour, outside the suite.
  - Cases: P6–P8.

#### Readings from the spec text (quotable)

- **R-a. RelayInfo.**
  - The client verifies `sig`, `relay_fp`, `valid_until ≥ now` and `akc` (if it holds an access key), and never
    caches the info (docs/03:535).
  - `akc` = SHA-256(`"SecMP-Q/1 akc"` ‖ key) (docs/03:222).
  - I4 fails whether the client compares against the RelayRef's `akc` or against the commitment of its own key
    (docs/03:229), so no case depends on which.
- **R-b. Frames.**
  - `k_c2r` is used client→relay and `k_r2c` relay→client.
  - The nonce is 0^16 ‖ u64be(counter), and the AD is `"SecMP-LINK/1 frame"` ‖ `sess_id`.
  - The plaintext is padded to 4336 B.
  - Counters start at 0 in each direction and are strict +1 (docs/03:563–566).
  - `cmd_seq` is only strictly increasing (docs/03:589); P22 tests this.
- **R-c. Tokens.**
  - The token is bound to `sess_id` and to the command's own `cmd_seq` (docs/03:618).
  - A token from another `cmd_seq` or another link is therefore ERR_TOKEN (docs/03:595, 600).
  - v1 keeps no double-spend list (M13).
- **R-d. Identical QUEUE_NEW.**
  - An identical QUEUE_NEW (same `recv_pk` and `send_pk`) answers OK_QUEUE_NEW without side effects, although its
    token and signature differ.
  - A known `recv_pk` with another `send_pk` is ERR_AUTH (docs/03:595, 629).
- **R-e. Multi-frame commands.**
  - LINK_PUT is 3 frames of 4160 + 4100 + 4100 B, with ONE response after the third frame, failures included
    (docs/03:815, 818).
  - LINKR is followed by two 0xFF CONT frames (docs/03:828).
  - CONT repeats the `cmd_seq` and is exempt from the increase check (docs/03:589).
- **R-f. Eviction.**
  - Eviction removes the oldest cell and reports its `cell_id` with `evicted_present` 1.
  - `evicted_id` is 0 when `evicted_present` is 0 (docs/03:614, 826).
- **R-g. MALFORMED answers.**
  - SKEY is answered with ERR_MALFORMED (docs/03:810).
  - FETCH with `ack ≥ next_cell_id` is MALFORMED (docs/03:585), carried as `present` 4 (reading OPEN-7).
- **R-h. One-time link data.**
  - A one-time blob is deleted atomically by the first consume.
  - Later consume calls answer `present` 0, `consumed` 1.
  - Owner status never consumes (docs/03:610).
- **R-i. Strict Ed25519.**
  - The strict verification of docs/03:140 applies to RelayInfoV1.`sig` and to every D.2 `sig`. The byte rules apply
    at decode (docs/03:152).
  - No case depends on the strict extras: bad signatures are made with a wrong key, or (I1) by flipping the low bit
    of S.

#### Questions and readings of `ref/` (proposal)

None of these changes a byte of the file; each is a behaviour that §8/§9 and the readings above leave open, pinned so
that `ref/` is total. They are in `ref/SPEC-QUESTIONS.md` with the quotes.

- **SQ-26 — a request whose `cmd_seq` ≤ `last`, for a multi-frame command or a response of more than one frame**
  (reading OPEN-5 against docs/03:597–601, 818, 833). Reading used: one ERR 6 frame, also for FETCH, FETCH_MULTI and
  LINK_GET, whose D.2 count does not apply to a request that is not executed; for LINK_PUT the relay still takes the
  two CONT frames and answers that one ERR 6 after the third, as every LINK_PUT answer (reading R-e). Only E23 (PING,
  one frame either way) is in the suite.
- **SQ-27 — frames while a LINK_PUT is pending** (docs/03:589, 818; reading OPEN-6). Reading used: only the next CONT
  of the pending LINK_PUT (same `cmd_seq`, `idx` 1 then 2) continues it; any other frame — a CONT with another
  `cmd_seq` or `idx`, another command, SKEY — is a LINK-level rejection like the orphan CONT (ref check
  `cont-expected`). No case.
- **SQ-28 — FETCH_MULTI with more entries in error than `F_M`, or a repeated `rid`** (docs/03:598, 813: `count ≤ 32`,
  `F_M` = 8). Reading used: the first `F_M` error frames in request order and nothing else; a repeated `rid` is
  checked and acknowledged per entry, and its queue's cells are selected once. No case.
- Readings adopted without a question (`ref/SPEC-QUESTIONS.md`, "Readings adopted without a question — REF-M5"):
  the order of checks inside each command (QUEUE_NEW: token, signature, known `recv_pk`, budget; SEND: `sid`,
  signature; FETCH and each FETCH_MULTI entry: `rid`, signature, `ack`; QUEUE_DEL: `rid`, signature; LINK_PUT: token,
  signature, `ld_id` known; owner status: entry and signature together); SKEY parses nothing after `cmd_seq`; a
  LINK_PUT on a consumption marker is ERR 5 until the marker expires; a consume-mode LINK_GET of an entry that is not
  one-time returns it and keeps it; owner status draws its dummy blob whether or not the signature verifies, consume
  mode only when it returns no blob; the padding is checked when the frame is opened, before the request decoder;
  the RelayInfo checks run in the order listed under "ref check"; the JSON names and shapes marked above.

**Outside the suite.** These belong to the Rust unit tests and the harness (07 M5 acceptance):
- zeroization on delete (docs/03:626);
- hour-bucket expiry and the sweeper (docs/03:624);
- rate limits and ERR 7 (docs/03:628);
- `RelayInfo` not being cached (docs/03:535);
- relay restart and re-creation of queues (docs/03:581, 585);
- LINK_PUT on a consumed marker (docs/03:610).
"""


def _names(layout, derived, *, cr=False, in_note="", notes=None):
    """`stream` n, … (R marks the relay's draws in a round trip); *`derived`* … — with the reviewer's notes."""
    notes = notes or {}
    stream = ", ".join(f"`{name}` {n}" + (" (R)" if cr and name in lc.RELAY_DRAWS else "") for name, n in layout)
    if in_note:
        stream = f"{stream or '—'} ({in_note})"
    derived = ", ".join(f"*`{d}`*" + (f" {notes[d]}" if d in notes else "") for d in derived)
    return "; ".join(p for p in (stream, derived) if p) or "—"


def _lens(values):
    lens = [len(v) for v in values]
    if len(lens) > 1 and len(set(lens)) == 1:
        return f"[{lens[0]} × {len(lens)}]"
    return "[" + ", ".join(map(str, lens)) + "]"


def _ids(ids):
    """[1, 2, 3, 7] → "1 … 3, 7" for runs longer than three."""
    out, k = [], 0
    while k < len(ids):
        j = k
        while j + 1 < len(ids) and ids[j + 1] == ids[j] + 1:
            j += 1
        out += [f"{ids[k]} … {ids[j]}"] if j - k >= 3 else [str(x) for x in ids[k:j + 1]]
        k = j + 1
    return ", ".join(out)


def _store(ctx, store):
    parts = [f"{ctx.name(q['rid'])}: [{_ids(q['cell_ids'])}], next {q['next_cell_id']}" for q in store["queues"]]
    parts += [f"L: {e['one_time']}, {e['expires_bucket']}, present {e['present']}, consumed {e['consumed']}"
              for e in store["linkdata"]]
    return "; ".join(parts) or "empty"


ASSERTED = {"P4": {"ck1": "`ss1`, `h0`, `ck1` = link-0003, asserted"},
            "P5": {"sess_id": "all six = link-0004, asserted"}}


def _outputs(ctx, row):
    ev, out = row["ev"], row["outputs"]
    cells = []
    for k, v in out.items():
        if k in ("resp", "resp_last"):
            text = f"`{k}` {_lens(v) if isinstance(v, list) else len(v)} ({row['answer']})"
        elif k == "link_post":
            text = f"`link_post` {{{v['c2r']}, {v['r2c']}, {v['cmd_seq']}}}"
        elif k == "store_post":
            text = f"`store_post` ({_store(ctx, v)})"
        elif isinstance(v, bool):
            text = f"`{k}` = {str(v).lower()}"
        elif isinstance(v, list):
            text = f"`{k}` {_lens(v)}"
        else:
            text = f"`{k}` {len(v)}"
        if k in ASSERTED.get(ev.name, {}):
            text += f" ({ASSERTED[ev.name][k]})"
        cells.append(text)
    return ", ".join(cells) + (f"; {ev.note}" if ev.note else "")


def _counters_cell(row):
    ev = row["ev"]
    text = lc._counters(row["counters"])
    if ev.name == "P22":
        s, rest = text.split(";", 1)
        text = f"**{s}**;{rest}"
    if ev.op == "send-fill":
        text += f" (`count` {lc.FILL_COUNT})"
    return text


def _positives(run):
    out = []
    for case, row in zip(run.cases, run.rows):
        ev = row.get("ev")
        if not isinstance(ev, lc.Ev) or ev.manipulation:
            continue
        counters = _counters_cell(row) if ev.party == "CR" else "—"
        inputs = _names(ev.stream, row["derived"], cr=ev.party == "CR", in_note=ev.in_note, notes=ev.derived_notes)
        out.append(f"| {ev.name} | {row['id']} | `{ev.op}` | {ev.party} | {case.fields.get('from', '—')} | "
                   f"{counters} | {inputs} | {_outputs(run.ctx, row)} | {ev.text} |")
    return "\n".join(out)


def _errors(run):
    out = []
    for row in run.rows:
        ev = row.get("ev")
        if not isinstance(ev, lc.Ev) or not ev.manipulation:
            continue
        inputs = _names(ev.stream, row["derived"], cr=True, in_note=ev.in_note, notes=ev.derived_notes)
        answer = row["answer"] + (f" ({ev.note})" if ev.note else "")
        out.append(f"| {ev.name} | {row['id']} | `{ev.op}` | `{ev.manipulation}` | {_counters_cell(row)} | "
                   f"{inputs} | {ev.text} | {answer}; unchanged | {ev.spec} |")
    return "\n".join(out)


def _x1(run):
    case = next(c for c in run.cases if c.op == "indist")
    groups = ", ".join("[" + ", ".join(cid[-4:] for cid in g) + "]" for g in case.fields["cases"])
    counts = ", ".join("[" + ", ".join(map(str, g)) + "]" for g in case.outputs["resp_counts"])
    return (f"| X1 | {lc.case_id(lc.SUITE, case.i)} | `indist` | CR | [{groups}] (ids `link-00nn`) | "
            f"`resp_counts` [{counts}], `frame_len` {case.outputs['frame_len']} |")


def _groups():
    return "\n".join(f"| {name} | {what} |" for name, what, _ in lc.X1_GROUPS)


def _relayinfo(run):
    out = []
    for case, row in zip(run.cases, run.rows):
        ev = row.get("ev")
        if not isinstance(ev, lc.Ri):
            continue
        outcome = f"reject / `{ev.rule}`" if ev.rule else "`outputs` {`accept`: true}"
        outcome += (" " if ev.rule else "") + ev.check_note if ev.check_note else ""
        out.append(f"| {ev.name} | {row['id']} | `{case.op}` | `{ev.manipulation}` | "
                   f"{_names([], row['derived'], notes=ev.derived_notes)} | {ev.text} | {outcome} |")
    return "\n".join(out)


def _check_cell(ev):
    return f"`{ev.rule}`" + (f" {ev.check_note}" if ev.check_note else "")


def _hs(run, table, with_inputs):
    out = []
    names = {h.name for h in table}
    for row in run.rows:
        ev = row.get("ev")
        if not isinstance(ev, lc.Hs) or ev.name not in names:
            continue
        text = ev.text.format(**{k: len(v) for k, v in (row.get("outputs") or {}).items()})
        cells = [ev.name, row["id"], f"`{ev.manipulation}`"]
        if with_inputs:
            cells.append(_names(ev.stream, row["derived"], notes=ev.derived_notes))
        cells += [text, _check_cell(ev)]
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out)


def _frames(run):
    out = []
    for row in run.rows:
        ev = row.get("ev")
        if not isinstance(ev, lc.Fr):
            continue
        text = ev.text if not ev.stream else f"stream {_names(ev.stream, [])}: {ev.text}"
        out.append(f"| {ev.name} | {row['id']} | {ev.party} | `{ev.manipulation}` | {text} | {_check_cell(ev)} |")
    return "\n".join(out)


def render() -> str:
    run = lc.run()
    pos = [e for e in lc.HANDSHAKE + lc.LINK_A if not e.manipulation]
    errs = [e for e in lc.LINK_A if e.manipulation]
    n_expect = sum(1 for c in run.cases if c.outputs is None or (c.fields or {}).get("expect") == "reject")
    return HEAD.format(
        total=len(run.cases), n_pos=len(pos), n_hs=len(lc.HANDSHAKE), n_pos_a=len(pos) - len(lc.HANDSHAKE),
        n_err=len(errs), n_x=1, n_ri=len(lc.RELAYINFO_CASES), n_ri_rej=len(lc.RELAYINFO_CASES) - 1,
        n_hs1=len(lc.HS1_REJECTS), n_s=len(lc.HS1_REJECTS) - 1, n_hs2=len(lc.HS2_REJECTS),
        n_fr=len(lc.FRAME_REJECTS), n_expect=n_expect,
        now=f"{lc.NOW:_}".replace("_", " "), bucket=f"{lc.NOW_BUCKET:_}".replace("_", " "), kid=lc.KID,
        valid_until=f"{lc.VALID_UNTIL:_}".replace("_", " "),
        validity=f"{lc.VALID_UNTIL - lc.NOW:_}".replace("_", " "), one_time=lc.ONE_TIME,
        expires_bucket=f"{lc.EXPIRES_BUCKET:_}".replace("_", " "), f=relay.F, f_m=relay.F_M,
        capacity=relay.QUEUE_CAPACITY, budget=lc.BUDGET_QUEUES, low_order=lc.LOW_ORDER.hex(),
        positives=_positives(run), errors=_errors(run), x1=_x1(run), groups=_groups(),
        relayinfo=_relayinfo(run), hs1=_hs(run, lc.HS1_REJECTS, True), hs2=_hs(run, lc.HS2_REJECTS, False),
        frames=_frames(run))


def main():
    text = render()
    OUT.write_text(text, encoding="utf-8")
    print(f"{OUT.name}: {len(text.splitlines())} lines")


if __name__ == "__main__":
    main()
